apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-uarr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-uarr
    app.kubernetes.io/part-of: tkrw-pr712-0075-0041-app
  name: devfile-sample-uarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-uarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-uarr
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0041-tenant/tkrw-pr712-0075-0041-app/devfile-sample-uarr@sha256:90a21f89ad3253f4eb1c3e0835bf213c0d7af62cca9f10989238fd98c098f26f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
